workspace '../SwiftyVK.xcworkspace'
inhibit_all_warnings!
use_frameworks!


# abstract_target 'TestingPods' do

  target 'SwiftyVK-Tests-iOS' do
    platform :ios, '8.0'
    pod 'OHHTTPStubs'
    pod 'OHHTTPStubs/Swift'
  end

  target 'SwiftyVK-Tests-OSX' do
    platform :osx, '10.10'
    pod 'OHHTTPStubs'
    pod 'OHHTTPStubs/Swift'
  end
# end
