codecov:
  branch: master

coverage:
  precision: 2
  round: up
  range: "80...100"

  ignore:
    - "Example/.*"
    - "Library/Tests/.*"
    - "Library/UI/.*"
    - "Library/Sources/Utils/Reachability.swift"
    - "Library/Sources/Utils/IDGenerator.swift"
    - "Library/Sources/Extensions/Numbers+Extensions.swift"
    - "Library/Sources/Extensions/URLOpener.swift"
    - "Library/Sources/Extensions/VKURLSession.swift"
