disabled_rules:
  - variable_name
  - trailing_whitespace
  - line_length
  - file_length
  - function_body_length
  - type_body_length
  - cyclomatic_complexity
  - type_name
  - valid_docs
  - nesting
  - statement_position
